namespace AutomaticAds.Utils;

public static class CountryMapping
{
    private static readonly Dictionary<string, CountryInfo> Countries = new()
    {
        { "AD", new CountryInfo("Andorra", "ca") },
        { "AE", new CountryInfo("United Arab Emirates", "ar") },
        { "AF", new CountryInfo("Afghanistan", "fa") },
        { "AG", new CountryInfo("Antigua and Barbuda", "en") },
        { "AI", new CountryInfo("Anguilla", "en") },
        { "AL", new CountryInfo("Albania", "sq") },
        { "AM", new CountryInfo("Armenia", "hy") },
        { "AO", new CountryInfo("Angola", "pt") },
        { "AQ", new CountryInfo("Antarctica", "en") },
        { "AR", new CountryInfo("Argentina", "es") },
        { "AS", new CountryInfo("American Samoa", "en") },
        { "AT", new CountryInfo("Austria", "de") },
        { "AU", new CountryInfo("Australia", "en") },
        { "AW", new CountryInfo("Aruba", "nl") },
        { "AX", new CountryInfo("Åland Islands", "sv") },
        { "AZ", new CountryInfo("Azerbaijan", "az") },
        { "BA", new CountryInfo("Bosnia and Herzegovina", "bs") },
        { "BB", new CountryInfo("Barbados", "en") },
        { "BD", new CountryInfo("Bangladesh", "bn") },
        { "BE", new CountryInfo("Belgium", "nl") },
        { "BF", new CountryInfo("Burkina Faso", "fr") },
        { "BG", new CountryInfo("Bulgaria", "bg") },
        { "BH", new CountryInfo("Bahrain", "ar") },
        { "BI", new CountryInfo("Burundi", "fr") },
        { "BJ", new CountryInfo("Benin", "fr") },
        { "BL", new CountryInfo("Saint Barthélemy", "fr") },
        { "BM", new CountryInfo("Bermuda", "en") },
        { "BN", new CountryInfo("Brunei", "ms") },
        { "BO", new CountryInfo("Bolivia", "es") },
        { "BQ", new CountryInfo("Caribbean Netherlands", "nl") },
        { "BR", new CountryInfo("Brazil", "pt") },
        { "BS", new CountryInfo("Bahamas", "en") },
        { "BT", new CountryInfo("Bhutan", "dz") },
        { "BV", new CountryInfo("Bouvet Island", "no") },
        { "BW", new CountryInfo("Botswana", "en") },
        { "BY", new CountryInfo("Belarus", "be") },
        { "BZ", new CountryInfo("Belize", "en") },
        { "CA", new CountryInfo("Canada", "en") },
        { "CC", new CountryInfo("Cocos Islands", "en") },
        { "CD", new CountryInfo("Democratic Republic of the Congo", "fr") },
        { "CF", new CountryInfo("Central African Republic", "fr") },
        { "CG", new CountryInfo("Republic of the Congo", "fr") },
        { "CH", new CountryInfo("Switzerland", "de") },
        { "CI", new CountryInfo("Côte d'Ivoire", "fr") },
        { "CK", new CountryInfo("Cook Islands", "en") },
        { "CL", new CountryInfo("Chile", "es") },
        { "CM", new CountryInfo("Cameroon", "fr") },
        { "CN", new CountryInfo("China", "zh") },
        { "CO", new CountryInfo("Colombia", "es") },
        { "CR", new CountryInfo("Costa Rica", "es") },
        { "CU", new CountryInfo("Cuba", "es") },
        { "CV", new CountryInfo("Cape Verde", "pt") },
        { "CW", new CountryInfo("Curaçao", "nl") },
        { "CX", new CountryInfo("Christmas Island", "en") },
        { "CY", new CountryInfo("Cyprus", "el") },
        { "CZ", new CountryInfo("Czech Republic", "cs") },
        { "DE", new CountryInfo("Germany", "de") },
        { "DJ", new CountryInfo("Djibouti", "fr") },
        { "DK", new CountryInfo("Denmark", "da") },
        { "DM", new CountryInfo("Dominica", "en") },
        { "DO", new CountryInfo("Dominican Republic", "es") },
        { "DZ", new CountryInfo("Algeria", "ar") },
        { "EC", new CountryInfo("Ecuador", "es") },
        { "EE", new CountryInfo("Estonia", "et") },
        { "EG", new CountryInfo("Egypt", "ar") },
        { "EH", new CountryInfo("Western Sahara", "ar") },
        { "ER", new CountryInfo("Eritrea", "ti") },
        { "ES", new CountryInfo("Spain", "es") },
        { "ET", new CountryInfo("Ethiopia", "am") },
        { "FI", new CountryInfo("Finland", "fi") },
        { "FJ", new CountryInfo("Fiji", "en") },
        { "FK", new CountryInfo("Falkland Islands", "en") },
        { "FM", new CountryInfo("Micronesia", "en") },
        { "FO", new CountryInfo("Faroe Islands", "fo") },
        { "FR", new CountryInfo("France", "fr") },
        { "GA", new CountryInfo("Gabon", "fr") },
        { "GB", new CountryInfo("United Kingdom", "en") },
        { "GD", new CountryInfo("Grenada", "en") },
        { "GE", new CountryInfo("Georgia", "ka") },
        { "GF", new CountryInfo("French Guiana", "fr") },
        { "GG", new CountryInfo("Guernsey", "en") },
        { "GH", new CountryInfo("Ghana", "en") },
        { "GI", new CountryInfo("Gibraltar", "en") },
        { "GL", new CountryInfo("Greenland", "kl") },
        { "GM", new CountryInfo("Gambia", "en") },
        { "GN", new CountryInfo("Guinea", "fr") },
        { "GP", new CountryInfo("Guadeloupe", "fr") },
        { "GQ", new CountryInfo("Equatorial Guinea", "es") },
        { "GR", new CountryInfo("Greece", "el") },
        { "GS", new CountryInfo("South Georgia", "en") },
        { "GT", new CountryInfo("Guatemala", "es") },
        { "GU", new CountryInfo("Guam", "en") },
        { "GW", new CountryInfo("Guinea-Bissau", "pt") },
        { "GY", new CountryInfo("Guyana", "en") },
        { "HK", new CountryInfo("Hong Kong", "zh") },
        { "HM", new CountryInfo("Heard Island", "en") },
        { "HN", new CountryInfo("Honduras", "es") },
        { "HR", new CountryInfo("Croatia", "hr") },
        { "HT", new CountryInfo("Haiti", "fr") },
        { "HU", new CountryInfo("Hungary", "hu") },
        { "ID", new CountryInfo("Indonesia", "id") },
        { "IE", new CountryInfo("Ireland", "en") },
        { "IL", new CountryInfo("Israel", "he") },
        { "IM", new CountryInfo("Isle of Man", "en") },
        { "IN", new CountryInfo("India", "hi") },
        { "IO", new CountryInfo("British Indian Ocean Territory", "en") },
        { "IQ", new CountryInfo("Iraq", "ar") },
        { "IR", new CountryInfo("Iran", "fa") },
        { "IS", new CountryInfo("Iceland", "is") },
        { "IT", new CountryInfo("Italy", "it") },
        { "JE", new CountryInfo("Jersey", "en") },
        { "JM", new CountryInfo("Jamaica", "en") },
        { "JO", new CountryInfo("Jordan", "ar") },
        { "JP", new CountryInfo("Japan", "ja") },
        { "KE", new CountryInfo("Kenya", "sw") },
        { "KG", new CountryInfo("Kyrgyzstan", "ky") },
        { "KH", new CountryInfo("Cambodia", "km") },
        { "KI", new CountryInfo("Kiribati", "en") },
        { "KM", new CountryInfo("Comoros", "ar") },
        { "KN", new CountryInfo("Saint Kitts and Nevis", "en") },
        { "KP", new CountryInfo("North Korea", "ko") },
        { "KR", new CountryInfo("South Korea", "ko") },
        { "KW", new CountryInfo("Kuwait", "ar") },
        { "KY", new CountryInfo("Cayman Islands", "en") },
        { "KZ", new CountryInfo("Kazakhstan", "kk") },
        { "LA", new CountryInfo("Laos", "lo") },
        { "LB", new CountryInfo("Lebanon", "ar") },
        { "LC", new CountryInfo("Saint Lucia", "en") },
        { "LI", new CountryInfo("Liechtenstein", "de") },
        { "LK", new CountryInfo("Sri Lanka", "si") },
        { "LR", new CountryInfo("Liberia", "en") },
        { "LS", new CountryInfo("Lesotho", "en") },
        { "LT", new CountryInfo("Lithuania", "lt") },
        { "LU", new CountryInfo("Luxembourg", "fr") },
        { "LV", new CountryInfo("Latvia", "lv") },
        { "LY", new CountryInfo("Libya", "ar") },
        { "MA", new CountryInfo("Morocco", "ar") },
        { "MC", new CountryInfo("Monaco", "fr") },
        { "MD", new CountryInfo("Moldova", "ro") },
        { "ME", new CountryInfo("Montenegro", "sr") },
        { "MF", new CountryInfo("Saint Martin", "fr") },
        { "MG", new CountryInfo("Madagascar", "mg") },
        { "MH", new CountryInfo("Marshall Islands", "en") },
        { "MK", new CountryInfo("Macedonia", "mk") },
        { "ML", new CountryInfo("Mali", "fr") },
        { "MM", new CountryInfo("Myanmar", "my") },
        { "MN", new CountryInfo("Mongolia", "mn") },
        { "MO", new CountryInfo("Macao", "zh") },
        { "MP", new CountryInfo("Northern Mariana Islands", "en") },
        { "MQ", new CountryInfo("Martinique", "fr") },
        { "MR", new CountryInfo("Mauritania", "ar") },
        { "MS", new CountryInfo("Montserrat", "en") },
        { "MT", new CountryInfo("Malta", "mt") },
        { "MU", new CountryInfo("Mauritius", "en") },
        { "MV", new CountryInfo("Maldives", "dv") },
        { "MW", new CountryInfo("Malawi", "en") },
        { "MX", new CountryInfo("Mexico", "es") },
        { "MY", new CountryInfo("Malaysia", "ms") },
        { "MZ", new CountryInfo("Mozambique", "pt") },
        { "NA", new CountryInfo("Namibia", "en") },
        { "NC", new CountryInfo("New Caledonia", "fr") },
        { "NE", new CountryInfo("Niger", "fr") },
        { "NF", new CountryInfo("Norfolk Island", "en") },
        { "NG", new CountryInfo("Nigeria", "en") },
        { "NI", new CountryInfo("Nicaragua", "es") },
        { "NL", new CountryInfo("Netherlands", "nl") },
        { "NO", new CountryInfo("Norway", "no") },
        { "NP", new CountryInfo("Nepal", "ne") },
        { "NR", new CountryInfo("Nauru", "en") },
        { "NU", new CountryInfo("Niue", "en") },
        { "NZ", new CountryInfo("New Zealand", "en") },
        { "OM", new CountryInfo("Oman", "ar") },
        { "PA", new CountryInfo("Panama", "es") },
        { "PE", new CountryInfo("Peru", "es") },
        { "PF", new CountryInfo("French Polynesia", "fr") },
        { "PG", new CountryInfo("Papua New Guinea", "en") },
        { "PH", new CountryInfo("Philippines", "en") },
        { "PK", new CountryInfo("Pakistan", "ur") },
        { "PL", new CountryInfo("Poland", "pl") },
        { "PM", new CountryInfo("Saint Pierre and Miquelon", "fr") },
        { "PN", new CountryInfo("Pitcairn", "en") },
        { "PR", new CountryInfo("Puerto Rico", "es") },
        { "PS", new CountryInfo("Palestine", "ar") },
        { "PT", new CountryInfo("Portugal", "pt") },
        { "PW", new CountryInfo("Palau", "en") },
        { "PY", new CountryInfo("Paraguay", "es") },
        { "QA", new CountryInfo("Qatar", "ar") },
        { "RE", new CountryInfo("Réunion", "fr") },
        { "RO", new CountryInfo("Romania", "ro") },
        { "RS", new CountryInfo("Serbia", "sr") },
        { "RU", new CountryInfo("Russia", "ru") },
        { "RW", new CountryInfo("Rwanda", "rw") },
        { "SA", new CountryInfo("Saudi Arabia", "ar") },
        { "SB", new CountryInfo("Solomon Islands", "en") },
        { "SC", new CountryInfo("Seychelles", "en") },
        { "SD", new CountryInfo("Sudan", "ar") },
        { "SE", new CountryInfo("Sweden", "sv") },
        { "SG", new CountryInfo("Singapore", "en") },
        { "SH", new CountryInfo("Saint Helena", "en") },
        { "SI", new CountryInfo("Slovenia", "sl") },
        { "SJ", new CountryInfo("Svalbard and Jan Mayen", "no") },
        { "SK", new CountryInfo("Slovakia", "sk") },
        { "SL", new CountryInfo("Sierra Leone", "en") },
        { "SM", new CountryInfo("San Marino", "it") },
        { "SN", new CountryInfo("Senegal", "fr") },
        { "SO", new CountryInfo("Somalia", "so") },
        { "SR", new CountryInfo("Suriname", "nl") },
        { "SS", new CountryInfo("South Sudan", "en") },
        { "ST", new CountryInfo("São Tomé and Príncipe", "pt") },
        { "SV", new CountryInfo("El Salvador", "es") },
        { "SX", new CountryInfo("Sint Maarten", "nl") },
        { "SY", new CountryInfo("Syria", "ar") },
        { "SZ", new CountryInfo("Swaziland", "en") },
        { "TC", new CountryInfo("Turks and Caicos Islands", "en") },
        { "TD", new CountryInfo("Chad", "fr") },
        { "TF", new CountryInfo("French Southern Territories", "fr") },
        { "TG", new CountryInfo("Togo", "fr") },
        { "TH", new CountryInfo("Thailand", "th") },
        { "TJ", new CountryInfo("Tajikistan", "tg") },
        { "TK", new CountryInfo("Tokelau", "en") },
        { "TL", new CountryInfo("East Timor", "pt") },
        { "TM", new CountryInfo("Turkmenistan", "tk") },
        { "TN", new CountryInfo("Tunisia", "ar") },
        { "TO", new CountryInfo("Tonga", "en") },
        { "TR", new CountryInfo("Turkey", "tr") },
        { "TT", new CountryInfo("Trinidad and Tobago", "en") },
        { "TV", new CountryInfo("Tuvalu", "en") },
        { "TW", new CountryInfo("Taiwan", "zh") },
        { "TZ", new CountryInfo("Tanzania", "sw") },
        { "UA", new CountryInfo("Ukraine", "uk") },
        { "UG", new CountryInfo("Uganda", "en") },
        { "UM", new CountryInfo("United States Minor Outlying Islands", "en") },
        { "US", new CountryInfo("United States", "en") },
        { "UY", new CountryInfo("Uruguay", "es") },
        { "UZ", new CountryInfo("Uzbekistan", "uz") },
        { "VA", new CountryInfo("Vatican City", "it") },
        { "VC", new CountryInfo("Saint Vincent and the Grenadines", "en") },
        { "VE", new CountryInfo("Venezuela", "es") },
        { "VG", new CountryInfo("British Virgin Islands", "en") },
        { "VI", new CountryInfo("U.S. Virgin Islands", "en") },
        { "VN", new CountryInfo("Vietnam", "vi") },
        { "VU", new CountryInfo("Vanuatu", "en") },
        { "WF", new CountryInfo("Wallis and Futuna", "fr") },
        { "WS", new CountryInfo("Samoa", "sm") },
        { "YE", new CountryInfo("Yemen", "ar") },
        { "YT", new CountryInfo("Mayotte", "fr") },
        { "ZA", new CountryInfo("South Africa", "en") },
        { "ZM", new CountryInfo("Zambia", "en") },
        { "ZW", new CountryInfo("Zimbabwe", "en") }
    };

    public static CountryInfo GetCountryInfo(string countryCode)
    {
        if (string.IsNullOrWhiteSpace(countryCode))
            return new CountryInfo(Constants.ErrorMessages.Unknown, "en");

        return Countries.TryGetValue(countryCode.ToUpper(), out var country)
            ? country
            : new CountryInfo(Constants.ErrorMessages.Unknown, "en");
    }

    public static string GetCountryName(string countryCode)
    {
        return GetCountryInfo(countryCode).Name;
    }

    public static string GetCountryLanguage(string countryCode)
    {
        return GetCountryInfo(countryCode).Language;
    }

    public static bool IsValidCountryCode(string countryCode)
    {
        return !string.IsNullOrWhiteSpace(countryCode) && Countries.ContainsKey(countryCode.ToUpper());
    }
}

public class CountryInfo
{
    public string Name { get; }
    public string Language { get; }

    public CountryInfo(string name, string language)
    {
        Name = name;
        Language = language;
    }
}